[project]
name = "axiomchat"
version = "0.1.0"
description = ""
authors = [
    {name = "T Vaishnavi",email = "tvhscv@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "networkx>=3.3",
    "scikit-learn (>=1.9.0,<2.0.0)",
    "pandas (>=3.0.3,<4.0.0)",
    "numpy (>=2.4.6,<3.0.0)",
    "matplotlib (>=3.11.0,<4.0.0)",
    "sentence-transformers (>=5.5.1,<6.0.0)",
    "ipykernel (>=7.3.0,<8.0.0)"
]
[tool.poetry]
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
